name: Docker CI hello world

on:
  push:
    paths: [ hello-world-docker-action/** ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run my own container action
        id: hello-action
        uses: actions/hello-world-docker-action
        with:
          who-to-greet: '@systream'

      - name: Output time set in the container
        run: echo "The time was ${{ steps.hello-action.outputs.time }} when the action said hello"
